	  <A HREF="/legal.html#3" target="_top"><FONT COLOR="FFFFFF" onMouseover="this.style.color='CCCCCC'" onMouseout="this.style.color=''"><B>PRIVACY POLICY</B></FONT></A> |
	  <A HREF="/sitemap/index.html"><B>Site Map</B></A> |
	  <A HREF="http://www.bboys.com/index.html" TARGET="_NEW"><B>bboys.com</B></A> |
	  <A HREF="http://www.stanlee.net"><B>stanlee.net</B></A> |
	  <A HREF="http://www.backstreetboys.com"><B>BSB.com</B></A> | 
	  <A HREF="http://corp.stanlee.net/index.html"><B>About Us (NASDAQ: SLEE)</B></A> |
	  <A HREF="/help/index.html"><B>Help</B></A> |
	  <A HREF="/legal.html"><B>Terms of Use</B></A> |
	  <A HREF="http://register.backstreetproject.com/registration/bsp_user_login.htm" onClick="pushURL(document.location, '.backstreetproject.com')"><B>Login</B></A><BR>
	  <FONT COLOR="003366">THE BACKSTREET PROJECT TM &amp; &copy; 2000 Stan Lee Media, Inc. &amp; KBNHA Enterprises, Inc. All rights reserved.</FONT>